package com.mcplugin.infrastructure.commands.subcommands;

import com.mcplugin.infrastructure.util.MessageUtil;
import org.bukkit.command.CommandSender;

public final class HelpCommand {

    private HelpCommand() {}

    public static void execute(CommandSender sender) {
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<gold>═══════════════════════════════════</gold>"));
        sender.sendMessage(MessageUtil.parse("<gold>  ✦ </gold><white>MC-Plugin </white><gray>— Available Commands</gray>"));
        sender.sendMessage(MessageUtil.parse("<gold>═══════════════════════════════════</gold>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp help</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Command list</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp checkver</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Check for plugin updates</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp updatejar</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Download and install update</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp setrad <nick> <value></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Set player radiation</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp toggleradview</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle radiation display</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp reload</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Reload plugin</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp modules list</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List plugin modules</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp modules enable </yellow><gray><module></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Enable a module</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp modules disable </yellow><gray><module></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Disable a module</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str dfc stats</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Reactor statistics</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str dfc assemble</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Assemble dark synthesis reactor</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str magnet assemble</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Assemble magnet</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str magnet stats</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Magnet statistics</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str lightning enable</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Enable lightning structure</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str lightning disable</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Disable lightning structure</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str lightning stats</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Lightning structure statistics</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vanish </yellow><gray><nick></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Hide/show player (vanish)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp notes</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Open notes</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List votes</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote create </yellow><gray><name> <flags></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Create a vote</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote </yellow><gray><name> [answer]</gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Vote / view results</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote delete </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Delete a vote</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote stats </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Vote statistics</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp power off</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Request server shutdown</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp power reboot</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Request server restart</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp power confirm</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Confirm power request (console)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp power undo</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Cancel power request</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp suicide</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Commit suicide (with confirmation)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp forcesuicide </yellow><gray><nick></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Force suicide another player</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp chgdim</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Open teleportation menu between worlds</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Open code panel</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane key add </yellow><gray><name> <code> [flags]</gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Add code panel key</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane key list</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List keys</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane key remove </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Remove key</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane key modify </yellow><gray><name> <new_code> [flags]</gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Modify key</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth forcelogin <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Force login a player</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth resetauth <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Delete player registration</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth chgpass <nick> <password></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Force change password</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth delsession <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Reset session</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth logout</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Logout from account</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp sethome </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Save home point</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp home </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ View home coordinates</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp delhome </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Delete home</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp listhomes</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List all homes</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp ophomels <player></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List player's homes (op)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp opdelhome <player> <name></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Delete player's home (op)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp chgop</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Interactive OP management</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp opwhitelist</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Manage OP whitelist</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp opwhitelist add <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Add player to OP whitelist</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp opwhitelist remove <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Remove from OP whitelist</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp opwhitelist list</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List OP whitelist</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp opwhitelist on/off</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle OP whitelist</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp whitelist</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Manage server whitelist</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp blacklist</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Manage server blacklist</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp punish ban <nick> [reason]</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Ban a player</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp punish mute <nick> [reason]</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Mute a player</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp punish kick <nick> [reason]</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Kick a player</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp punish warn <nick> [reason]</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Warn a player</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp punish crash <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Crash a player's client (particles)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp check <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Freeze player for anticheat check</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp uncheck <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Unfreeze player</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp ac overview</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Anti-cheat overview</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp ac checks</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List anticheat checks</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp ac players</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List flagged players</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp ac player <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Player anticheat stats</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp expsplit</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle experience splitting</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp invsee <player></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ View and edit player's inventory</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp endersee <player></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ View and edit player's ender chest</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp setspawn</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Set spawn point (asks confirmation to override)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp spawn</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Teleport to spawn (standard) or show coords (legit)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp item int list</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List item integrity</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp item int set <value></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Set held item integrity</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp item int add <value></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Add item integrity</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp bc <message></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Broadcast a message</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp maint</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle maintenance mode</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp report <nick> [reason]</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Report a player</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp reports list</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List reports</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp reports add <id> <name></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Add report to mod queue</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp reports remove <id></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Remove from mod queue</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp modreport <name></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Open moderation queue</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp repstatus</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Show your report status</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp askcords <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Ask player for coordinates</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp cilist</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List civilizations</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<gold>═══════════════════════════════════</gold>"));
        sender.sendMessage(MessageUtil.parse("<gold>  ✦ </gold><white>Player Settings</white>"));
        sender.sendMessage(MessageUtil.parse("<gold>═══════════════════════════════════</gold>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp togglebb</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle bossbar</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp togglesb</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle scoreboard</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp toggleping</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle ping sound</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp togglespeed</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle speed display</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp togglefly</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle elytra boost on jump</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp toggleautocraft</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Toggle auto-craft</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<gold>═══════════════════════════════════</gold>"));
        sender.sendMessage("");
    }
}
