name: MC-Plugin

version: 1.4

main: com.mcplugin.Main

api-version: "1.21.11"

author: MrCotik337

load: POSTWORLD

commands:

  cp_click:
    description: Internal code panel click command
    usage: /cp_click

  mp:
    description: Control the MC-Plugin
    usage: /mp
    permission: mcplugin.reload

  reactor:
    description: Assemble reactor structures
    usage: /reactor assemble <type>

permissions:

  mcplugin.command.reload:
    description: Allows plugin reload
    default: op

  mcplugin.command.chgdim:
    description: Allows teleportation between dimensions (/mp chgdim)
    default: op

  mcplugin.overload.logs:
    description: Receive overload protection messages in chat
    default: op

  mcplugin.gmprotect.bypass:
    description: Позволяет сменить режим игры в защищённых мирах
    default: op

  mcplugin.creative.bypass:
    description: Allows bypassing the creative item validator (oversized items)
    default: op

  mcplugin.chat.filter.bypass:
    description: Allows bypassing the chat filter (profanity filter)
    default: op