package com.mcplugin.commands.subcommands;

import com.mcplugin.util.MessageUtil;
import org.bukkit.command.CommandSender;

public final class HelpCommand {

    private HelpCommand() {}

    public static void execute(CommandSender sender) {
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<gold>═══════════════════════════════════</gold>"));
        sender.sendMessage(MessageUtil.parse("<gold>  ✦ </gold><white>MC-Plugin </white><gray>— Available Commands</gray>"));
        sender.sendMessage(MessageUtil.parse("<gold>═══════════════════════════════════</gold>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp help</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Command list</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp checkver</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Check for plugin updates</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp updatejar</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Download and install update</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp checkrad </yellow><gray>[nick]</gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Check radiation (without nick — your own)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp setrad <nick> <value></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Set player radiation</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp reload</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Reload plugin</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp modules list</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List plugin modules</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp modules enable </yellow><gray><module></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Enable a module</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp modules disable </yellow><gray><module></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Disable a module</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str dfc stats</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Reactor statistics</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str dfc assemble</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Assemble dark synthesis reactor</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str magnet assemble</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Assemble magnet</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str magnet stats</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Magnet statistics</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str lightning enable</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Enable lightning structure</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str lightning disable</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Disable lightning structure</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp str lightning stats</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Lightning structure statistics</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vanish </yellow><gray><nick></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Hide/show player (vanish)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp notes</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Open notes</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List votes</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote create </yellow><gray><name> <title> <desc> -answer_N:... -time:...</gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Create a vote</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote </yellow><gray><name> [answer_number]</gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Vote / view results</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote delete </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Delete a vote (with confirmation)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp vote stats </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Vote statistics (results, graph)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp power off</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Request server shutdown</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp power reboot</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Request server restart</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp power confirm</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Confirm power request (console)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp power undo</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Cancel power request</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp suicide</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Commit suicide (with confirmation, no cancel)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp chgdim</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Open teleportation menu between worlds</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Open code panel</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane key add </yellow><gray><name> <code> [flags]</gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Add code panel key</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane key list</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List keys</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane key remove </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Remove key</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp codepane key modify </yellow><gray><name> <new_code> [flags]</gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Modify key</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth forcelogin <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Force login a player</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth resetauth <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Completely delete player registration</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth chgpass <nick> <password></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Force change password</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth delsession <nick></yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Reset session (registration remains)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp auth logout</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Logout from account</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp sethome </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Save home point (1-16 chars, max 10)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp home </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ View home point coordinates</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp delhome </yellow><gray><name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Delete home point</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp listhomes</yellow>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List all homes with coordinates</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<yellow>/mp ophomels </yellow><gray><player></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ List player's homes (operator)</gray>"));
        sender.sendMessage(MessageUtil.parse("<yellow>/mp opdelhome </yellow><gray><player> <name></gray>"));
        sender.sendMessage(MessageUtil.parse(" <gray>└ Delete player's home (operator)</gray>"));
        sender.sendMessage("");
        sender.sendMessage(MessageUtil.parse("<gold>═══════════════════════════════════</gold>"));
        sender.sendMessage("");
    }
}
