package com.mcplugin.commands.subcommands;

import org.bukkit.command.CommandSender;

public final class HelpCommand {

    private HelpCommand() {}

    public static void execute(CommandSender sender) {
        sender.sendMessage("");
        sender.sendMessage("§6═══════════════════════════════════");
        sender.sendMessage("§6  ✦ §fMC-Plugin §7— Доступные команды");
        sender.sendMessage("§6═══════════════════════════════════");
        sender.sendMessage("");
        sender.sendMessage("§e/mp help");
        sender.sendMessage(" §7└ Список команд");
        sender.sendMessage("");
        sender.sendMessage("§e/mp checkver");
        sender.sendMessage(" §7└ Проверить наличие обновлений плагина");
        sender.sendMessage("§e/mp updatejar");
        sender.sendMessage(" §7└ Скачать и установить обновление");
        sender.sendMessage("");
        sender.sendMessage("§e/mp checkrad §7[ник]");
        sender.sendMessage(" §7└ Проверить радиацию (без ника — свою)");
        sender.sendMessage("§e/mp setrad <ник> <значение>");
        sender.sendMessage(" §7└ Установить радиацию игрока");
        sender.sendMessage("");
        sender.sendMessage("§e/mp reload");
        sender.sendMessage(" §7└ Перезагрузить плагин");
        sender.sendMessage("");
        sender.sendMessage("§e/mp modules list");
        sender.sendMessage(" §7└ Список модулей плагина");
        sender.sendMessage("§e/mp modules enable §7<модуль>");
        sender.sendMessage(" §7└ Включить модуль");
        sender.sendMessage("§e/mp modules disable §7<модуль>");
        sender.sendMessage(" §7└ Отключить модуль");
        sender.sendMessage("");
        sender.sendMessage("§e/mp str dfc stats");
        sender.sendMessage(" §7└ Статистика реактора");
        sender.sendMessage("§e/mp str dfc assemble");
        sender.sendMessage(" §7└ Собрать реактор тёмного синтеза");
        sender.sendMessage("§e/mp str magnet assemble");
        sender.sendMessage(" §7└ Собрать магнит");
        sender.sendMessage("§e/mp str magnet stats");
        sender.sendMessage(" §7└ Статистика магнита");
        sender.sendMessage("§e/mp str lightning enable");
        sender.sendMessage(" §7└ Включить структуру молний");
        sender.sendMessage("§e/mp str lightning disable");
        sender.sendMessage(" §7└ Выключить структуру молний");
        sender.sendMessage("§e/mp str lightning stats");
        sender.sendMessage(" §7└ Статистика структуры молний");
        sender.sendMessage("");
        sender.sendMessage("§e/mp vanish §7<ник>");
        sender.sendMessage(" §7└ Скрыть/показать игрока (ваниш)");
        sender.sendMessage("");
        sender.sendMessage("§e/mp notes");
        sender.sendMessage(" §7└ Открыть заметки");
        sender.sendMessage("");
        sender.sendMessage("§e/mp vote");
        sender.sendMessage(" §7└ Список голосований");
        sender.sendMessage("§e/mp vote create §7<название> <заголовок> <описание> -answer_N:... -time:...");
        sender.sendMessage(" §7└ Создать голосование");
        sender.sendMessage("§e/mp vote §7<название> [номер_ответа]");
        sender.sendMessage(" §7└ Проголосовать / посмотреть результаты");
        sender.sendMessage("§e/mp vote delete §7<название>");
        sender.sendMessage(" §7└ Удалить голосование (с подтверждением)");
        sender.sendMessage("§e/mp vote stats §7<название>");
        sender.sendMessage(" §7└ Статистика голосования (результаты, график)");
        sender.sendMessage("");
        sender.sendMessage("§e/mp power off");
        sender.sendMessage(" §7└ Запросить выключение сервера");
        sender.sendMessage("§e/mp power reboot");
        sender.sendMessage(" §7└ Запросить перезагрузку сервера");
        sender.sendMessage("§e/mp power confirm");
        sender.sendMessage(" §7└ Подтвердить запрос (консоль)");
        sender.sendMessage("§e/mp power undo");
        sender.sendMessage(" §7└ Отменить запрос");
        sender.sendMessage("");
        sender.sendMessage("§e/mp suicide");
        sender.sendMessage(" §7└ Совершить суицид (с подтверждением, без отмены)");
        sender.sendMessage("");
        sender.sendMessage("§e/mp chgdim");
        sender.sendMessage(" §7└ Открыть меню телепортации между мирами");
        sender.sendMessage("");
        sender.sendMessage("§e/mp codepane");
        sender.sendMessage(" §7└ Открыть кодовую панель");
        sender.sendMessage("§e/mp codepane key add §7<название> <код> [флаги]");
        sender.sendMessage(" §7└ Добавить ключ кодовой панели");
        sender.sendMessage("§e/mp codepane key list");
        sender.sendMessage(" §7└ Список ключей");
        sender.sendMessage("§e/mp codepane key remove §7<название>");
        sender.sendMessage(" §7└ Удалить ключ");
        sender.sendMessage("§e/mp codepane key modify §7<название> <новый_код> [флаги]");
        sender.sendMessage(" §7└ Изменить ключ");
        sender.sendMessage("");
        sender.sendMessage("§e/mp auth forcelogin <ник>");
        sender.sendMessage(" §7└ Принудительно авторизовать игрока");
        sender.sendMessage("§e/mp auth resetauth <ник>");
        sender.sendMessage(" §7└ Полностью удалить регистрацию игрока");
        sender.sendMessage("§e/mp auth chgpass <ник> <пароль>");
        sender.sendMessage(" §7└ Принудительно сменить пароль");
        sender.sendMessage("§e/mp auth delsession <ник>");
        sender.sendMessage(" §7└ Сбросить сессию (регистрация остаётся)");
        sender.sendMessage("");
        sender.sendMessage("§e/mp auth logout");
        sender.sendMessage(" §7└ Выйти из аккаунта (logout)");
        sender.sendMessage("");
        sender.sendMessage("§e/mp sethome §7<название>");
        sender.sendMessage(" §7└ Сохранить домашнюю точку (1-16 символов, макс. 10)");
        sender.sendMessage("§e/mp home §7<название>");
        sender.sendMessage(" §7└ Показать координаты домашней точки");
        sender.sendMessage("§e/mp delhome §7<название>");
        sender.sendMessage(" §7└ Удалить домашнюю точку");
        sender.sendMessage("§e/mp listhomes");
        sender.sendMessage(" §7└ Список всех домов с координатами");
        sender.sendMessage("");
        sender.sendMessage("§e/mp ophomels §7<игрок>");
        sender.sendMessage(" §7└ Список домов игрока (оператор)");
        sender.sendMessage("§e/mp opdelhome §7<игрок> <название>");
        sender.sendMessage(" §7└ Удалить дом игрока (оператор)");
        sender.sendMessage("");
        sender.sendMessage("§6═══════════════════════════════════");
        sender.sendMessage("");
    }
}
